INCDIR = ../

CC ?= cc
CFLAGS += -Wall
DEFS = -DPLATFORM_LINUX
AR = ar -ru
RM = rm -f

OBJS    = cmnllib.o

cmnllib.a : $(OBJS) 
	$(AR) cmnllib.a $(OBJS)
	
cmnllib.o: cmnllib.c
	$(CC) $(CPPFLAGS) $(CFLAGS) $(DEFS) $(LDFLAGS) -I $(INCDIR) -c cmnllib.c -o cmnllib.o

clean :
	$(RM) *.o *.a
